# Generated by Django 5.2.17 on 2026-09-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('pseudo', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
